// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {browser} from '../models';

export function DropSchema():Promise<void>;

export function FetchFirefox(arg1:string):Promise<void>;

export function InstallFirefox(arg1:string):Promise<void>;

export function LaunchFirefox(arg1:string,arg2:string):Promise<void>;

export function SyncBrowsers():Promise<Array<browser.Browser>>;
