// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchFirefox(arg1) {
  return window['go']['raven']['App']['FetchFirefox'](arg1);
}

export function FetchVersions() {
  return window['go']['raven']['App']['FetchVersions']();
}

export function InstallFirefox(arg1) {
  return window['go']['raven']['App']['InstallFirefox'](arg1);
}

export function LaunchFirefox(arg1, arg2) {
  return window['go']['raven']['App']['LaunchFirefox'](arg1, arg2);
}
