// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function FetchFirefox(arg1:string):Promise<void>;

export function FetchVersions():Promise<Array<types.BrowserListItem>>;

export function InstallFirefox(arg1:string):Promise<void>;

export function LaunchFirefox(arg1:string,arg2:string):Promise<void>;
