// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';

export function Fetch():Promise<void>;

export function FetchVersions():Promise<Array<types.BrowserListItem>>;

export function Run():Promise<void>;
