// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Fetch() {
  return window['go']['main']['App']['Fetch']();
}

export function Run() {
  return window['go']['main']['App']['Run']();
}
